version: '3.4'

services:
  botplayer-tauz2.0:
    container_name: bot-container
    image: jaofreire/bot-playertauz-image:latest
    build:
      context: .
      dockerfile: Bot-PLayer-Tauz2.0/Dockerfile
    environment:
      ConnectionString: mongodb://rostname:password@mongo-container:27017/Musics
      State: production
    depends_on: 
     - mongodb
    networks:
     - net-bot


  mongodb:
   container_name: mongo-container
   image: mongo:latest
   ports: 
    - 27017:27017
   environment:
     MONGO_INITDB_ROOT_USERNAME: rostname
     MONGO_INITDB_ROOT_PASSWORD: password
   networks:
    - net-bot

  mongo-express:
    container_name: mongoexpress-container
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rostname
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://rostname:password@mongo-container:27017/


networks:
  net-bot:
   driver: bridge  