version: '3.4'

services:
  botplayer-tauz2.0:
    container_name: bot-container
    image: jaofreire/bot-playertauz-image:latest
    # build:
    #   context: .
    #   dockerfile: Bot-PLayer-Tauz2.0/Dockerfile
    networks:
     - net-bot


  mongo:
   container_name: mongo-container
   image: mongo:latest
   restart: always
   ports:
    - 27017:27017
   env_file:
    - Bot-PLayer-Tauz2.0/prod.env
   networks:
    - net-bot



networks:
  net-bot:
   driver: bridge
